### ISSUE TITLE
NullReferenceException at the DesignMode checker

### ISSUE THREAD

**Issue by Zimbo23** [opentk/GLControl#1] opened 2021-01-29 00:15 UTC
There is a Null Reference Exception at

GLControl.cs,
DetermineIfThisIsDesignMode().

In the for-Loop, control.Site is Null.

It happened to me when i was trying to run the given test forms.

**Comment by seanofw** [comment] 2021-02-19 00:36
I still can't reproduce this; it runs fine locally for me, both at runtime, and in the new VS2019 designer for .NET Core.  (I am using Visual Studio Professional 2019, 16.8.3, with the new designer enabled.)

- Is this happening at runtime or at design time?
- What version of Visual Studio are you using?  (Exact version number, and Professional, Enterprise, Ultimate, or Community edition?)
- Did you enable the new Windows Forms designer for .NET Core, or are you trying to use the old Windows Forms designer?

Note:  The old WinForms designer doesn't support .NET Core, so if you want to use .NET Core WinForms in Visual Studio, you'll have to enable the new designer.

**Comment by seanofw** [comment] 2021-02-19 01:12
Also, if you could, please try the code in this pull request and see if it resolves the issue:

https://github.com/opentk/GLControl/pull/2

**Comment by Zimbo23** [comment] 2021-02-21 14:42
- The exception happens at runtime.
- I'm using VS 2019 Community, version 16.8.4
- I'm using the new .NET Core designer.

The new code worked fine for me, at design time and at runtime.

**Comment by seanofw** [comment] 2021-02-21 14:47
Well, I'm glad that the fix works, and I'll merge that in properly now that it does; but I still can't figure out why you were getting the exception in the first place.  What version of .NET Core are you using?  All of my testing has been in .NET Core 3.1, so maybe if you're using .NET Core 5, that could affect it.

At design time, do you correctly see the spinning cube inside the GLControl?

**Comment by Zimbo23** [comment] 2021-02-21 15:11
I'm using .NET Core 3.1, too.

And I can see the spinning cubes.

**Comment by seanofw** [comment] 2021-02-23 15:30
All right, well, it sounds like the fix works in both cases, so I'll take that as confirmation.  We'll get the pull request merged into the `master` branch.  Thanks for putting up with the bugs while we polish things up!

**Closed by seanofw** 2021-02-23 15:30 UTC
